### ISSUE TITLE
Issues observed during the workshop

### ISSUE THREAD

**Issue by mabraham** [ENCCS/cmake-workshop#19]
I'll edit this as we go along

* Suggest introduce targets earlier, as it the material on syntax and system introspection makes more sense if students aren't being distracted by `PRIVATE` etc.
* Graphic for https://enccs.github.io/cmake-workshop/hello-cmake/#what-is-cmake would be easier to understand if the "pages" that corresponding to source files were named also with words, and the cylinder was labelled as a binary executable.
* users are not experts at unpacking tarballs, so we need to give them a command to unpack them. Using `.zip` is probably more friendly for new programmers than `.tar.gz` or `.tar.bz2`, as they may have seen those in other contexts
* text should mention that `CMakeLists.txt` should be stored in git, but not the makefiles it generates
* dereference operator is formally `${}` but that's not how it looks when used, so an example would help clarify.
* the first exercise set `BUILD_SHARED_LIBS` on the command-line, which might have been something a student would ask about. (Suggest we don't set it at all there, as it brings in questions about the cache and variables that haven't yet been covered in the syntax lesson and is a topic itself much later.) Then the second exercise said "Define the BUILD_SHARED_LIBS variable" but didn't say whether to put it on the cmake command line or in the `CMakeLists.txt` file. Perhaps all of this makes more sense if we teach the students to manage setting variables using a non-standard name, so that questions of over-writing the cache do not apply.
* we should number the exercises in the sphinx lesson and use matching numbers in downloaded files and the subdirectories they contain
* the dependent-option exercise solution can make a library of the same name in both STATIC and SHARED. That causes an error. We should rather expose a variable that the user can use to toggle between them, rather than toggle both of them on or off. See #20
* "the build tree" is a sub-heading of "flow control" and probably should not be
* ctest operates at a higher level than a unit-test framework like Catch2 or GoogleTest, or your own binary, or some python script, etc. Perhaps a diagram is good for that.

Exercise 16
* exercise numbers need to appear also in the sphinx lesson titles, like "Exercise 16: Configure a file"
* exercise 16 has too many variables to configure in config.h. A few values and a string is enough.
* exercise 16 sets e.g. `_HAS_FPU` from querying `cmake_host_system_information` for `HAS_FPU` and then uses it in `config.h` to set preprocessor variable `HAS_FPU`. There's no need to introduce underscore prefixing.
* teach where `config.h` will be written before students have to use that knowledge
* provide URL links to docs for configure_file, target_include_directories as well as command lines to query for the offline docs

Exercise 25
* shouldn't fc_mangle.h be included from the Cxx*cpp files? It declares things called from within the source file, not things the source file defines for its clients
* since DSCAL is a macro, it probably shouldn't get a :: prefix, because that should be in the macro definition (or not) already
* omit the unnecessary instructions about `MACRO_NAMESPACE`
* the math folder and library, and the two .cpp files within it are moving parts that don't contribute to the topic of the exercise. A single cpp file that calls the BLAS and LAPACK functions would be easier for students to understand. (During the exercise, I had no time to look at linear-algebra.cpp at all.)

**Comment by wikfeldt** [comment]
- all exercises should be numbered to make them easier to find
- consider merging short exercises into longer breakout room sessions

**Comment by zhmurov** [comment]
It would be useful to go through the solution after listeners are back from BO rooms

**Comment by qianglise** [comment]
maybe give more time for the first exercise

**Comment by zhmurov** [comment]
Ex. 21: the questions below the source tree should be connected to a specific folder. Though it may be only relevant to the simplified version of the exercise that wee have got:)

**Comment by robertodr** [comment]
I've "unpacked" the list into separate issues. Some of them were fixed during the workshop already.
