### ISSUE TITLE
Automata example: show how to run it

### ISSUE THREAD

**Issue by bast** [ENCCS/cmake-workshop#23]
- It can be a bit surprising that the binary is under `build/src`.
- There does not seem to be an example on how to run it. If one tries the binary as is, it throws an ugly error directly from C++.

**Comment by robertodr** [comment]
> * It can be a bit surprising that the binary is under `build/src`.

This is on purpose, as one of the tasks in the exercise is to browse the build tree and find how it is laid out in comparison with the source tree. I decided **not to** set `CMAKE_RUNTIME_OUTPUT_DIRECTORY` and co. to avoid overloading the number of new variables presented at once.
 
> * There does not seem to be an example on how to run it. If one tries the binary as is, it throws an ugly error directly from C++.

I am amending this.

**Comment by bast** [comment]
+1 for point 1.
