### ISSUE TITLE
16_configure exercise can be simplified

### ISSUE THREAD

**Issue by bast** [ENCCS/cmake-workshop#29]
The `configure_file` part is the essence but it can get a bit lost in the `foreach` and other "distractions".

**Comment by bast** [comment]
We should try to only configure one or two variables to really see how it works. I would leave out the `foreach`.

**Comment by robertodr** [comment]
Instructions are out of date with scaffold. These were not updated after I changed the exercise layout yesterday :facepalm:

**Comment by robertodr** [comment]
From #19 

>  - exercise numbers need to appear also in the sphinx lesson titles, like "Exercise 16: Configure a file"
> - exercise 16 has too many variables to configure in config.h. A few values and a string is enough.
> - exercise 16 sets e.g. _HAS_FPU from querying cmake_host_system_information for HAS_FPU and then uses it in config.h to set preprocessor variable HAS_FPU. There's no need to introduce underscore prefixing.
> - teach where config.h will be written before students have to use that knowledge
> - provide URL links to docs for configure_file, target_include_directories as well as command lines to query for the offline docs
