### ISSUE TITLE
workshop organization

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/cmake-workshop#3]
i'll use this issue to track progress with the event organization. This list can be reused for future events

Todos:

- [x] recruit instructors
- [x] recruit helpers
- [x] prepare material
- [x] decide dates
- [x] create event webpage
- [x] create registration form with max-participants 50% over capacity 
- [x] open registration
- [x] advertise event
- [x] close registration
- [x] approve participants (assume 25% no-shows)
- [x] inform people on waiting list
- [ ] (optional) ask invited participants to confirm attendance
- [x] set up zoom link and hackMD doc
- [ ] (optional) schedule installation help zoom session
- [x] send installation instructions 1-2 weeks before event. Request early cancellation
- [x] invite from the waiting list in order of registration date
- [ ] (optional) organize helper training/coordination session
- [ ] set up post-workshop survey form
- [ ] after ws or on last day: send out post-workshop survey 
- [ ] after ws: debrief and analyze survey results

**Comment by mabraham** [comment]
Good initiative! Maybe a good workshop to run on SNIC cloud?

**Comment by wikfeldt** [comment]
hmm, yes probably! What do you think @robertodr ? I've been intending to test SNIC cloud soon and for this workshop we can have it as optional since some people probably already have compilers and can easily install CMake

**Comment by robertodr** [comment]
I think we recruited helpers already for this one, didn't we? I agree that SNIC cloud would be a very good fallback option. How do we get set up there? It seems the call for a project there is now closed?

**Comment by wikfeldt** [comment]
yes i hope we have all the helpers but left it unticked just in case. I realized that as Zoom host i'll probably have to stay in main room, there's often some logistics with sending people back into BO rooms that get kicked out and such. How many helpers do we then have?

I'll send in an application for snic cloud and start playing with it

**Comment by robertodr** [comment]
Ah, yes. I had forgotten one of us has to stay in the main room. We had counted 6 helpers (Mark, Jing, Qiang, Radovan, you and me) and 6 attendees per helper. Maybe Artem is willing to be a helper?
