### ISSUE TITLE
consider adding "Exercise" to exercise boxes

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/cmake-workshop#30]
- makes it clearar that it's an exercise (newcomers might get confused by wrench, pen and exclamation mark boxes)
- makes the exercises `CTRL-F` -able

**Comment by robertodr** [comment]
Very good, yes. I've opened this one https://github.com/coderefinery/sphinx-lesson/issues/56 as it might also be helpful to have numbering well-visible (and automatic)
