### ISSUE TITLE
Consider removing the C++/Fortran episode

### ISSUE THREAD

**Issue by robertodr** [ENCCS/cmake-workshop#31]
* It's rather niche.
* It's more about how the languages differ and how you can make them talk, than any generally applicable CMake tool or trick.

**Comment by robertodr** [comment]
Can be moved to an "extra" section in the lesson:
- not part of the "canonical" set of episodes.
- can be added if there's significant request when people sign up.
- attendees can be directed there if there are questions on the topic.

**Comment by zhmurov** [comment]
+1 fo "extra" section. There were people interested in this according to survey.

**Comment by robertodr** [comment]
From #19 

> - shouldn't fc_mangle.h be included from the Cxx*cpp files? It declares things called from within the source file, not things the source file defines for its clients
> - since DSCAL is a macro, it probably shouldn't get a :: prefix, because that should be in the macro definition (or not) already
> - omit the unnecessary instructions about MACRO_NAMESPACE
> - the math folder and library, and the two .cpp files within it are moving parts that don't contribute to the topic of the exercise. A single cpp file that calls the BLAS and LAPACK functions would be easier for students to understand. (During the exercise, I had no time to look at linear-algebra.cpp at all.)
