### ISSUE TITLE
Add exercise showing the use of the visibility levels

### ISSUE THREAD

**Issue by robertodr** [ENCCS/cmake-workshop#32]
The `PRIVATE`/`INTERFACE`/`PUBLIC` visibility levels are covered in one episode, but the differences between the 3 are not immediately obvious. In particular, the use of `INTERFACE` to express transitive dependencies only can be challenging to understand. Add one or more exercises showing the when to use each.

**Comment by zhmurov** [comment]
I think it would be good to iterate on these when they appear before they explained (maybe just by saying that these are visibility levels and they will be talked about later). I had a question on one of the breakout rooms.

**Comment by robertodr** [comment]
Yep, I had a question on them too and also questions on what exactly `INTERFACE` means and whether it is actually ever used in practice.
