### ISSUE TITLE
update setup page

### ISSUE THREAD

**Issue by wikfeldt** [ENCCS/cmake-workshop#5]
currently MPI instructions from december workshop.

Most material from on https://github.com/ENCCS/cmake-workshop-setup/blob/main/README.md should be moved here.

Plan: (@robertodr FYI)
-  i'll add a code block with the environment.yml file from https://github.com/ENCCS/cmake-workshop-setup
- i'll add a link to https://github.com/ENCCS/cmake-workshop-setup for running mybinder

**Comment by wikfeldt** [comment]
actually, is there any reason not to move environment.yml and the binder action from https://github.com/ENCCS/cmake-workshop-setup/ to this repo and add a launch binder button here?

**Comment by robertodr** [comment]
No reason at all, actually. We should merge the two repos, less change of things getting out of sync.
