### ISSUE TITLE
`The case of CMake commands and variables does not matter: the DSL is case-insensitive.` is wrong in hello-cmake.rst

### ISSUE THREAD

**Issue by liaoya** [ENCCS/cmake-workshop#53]
I like cmake-workshop and I want you can check the following. You can ignore it if I'm wrong

`hello-cmake.rst` says `The case of CMake commands and variables does not matter: the DSL is case-insensitive.`

in <https://cmake.org/cmake/help/latest/manual/cmake-language.7.html#variables> says `Variable names are case-sensitive`.

I create the following `CMakeLists.txt` to verify it

```CMake
cmake_minimum_required(VERSION 3.18)
project(foo NONE)

set(abc "123")
set(ABC "321")

message("lower case variable \${abc}: ${abc}")
message("upper case variable \${ABC}: ${ABC}")
```

The output of running `cmake -S. -Bbuild` is

```text
lower case variable ${abc}: 123
upper case variable ${ABC}: 321
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/project/build
```

**Comment by mabraham** [comment]
Thanks, you're right! I proposed a fix
